services:
  airflow:
    image: clobee-harbor.shop/library/clobee-crawling-airflow:1.5
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${PROD__AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      # AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${DEV__AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__RBAC: "true"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./crawling_code:/opt/airflow/crawling_code
      - ./app.py:/opt/airflow/app.py
      - ./brand_mapping.py:/opt/airflow/brand_mapping.py
    ports:
      - "8080:8080"  # airflow
      - "8000:8000"  # FastAPI
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username ${AIRFLOW__USER} --password ${AIRFLOW__PW} --firstname admin --lastname user --role Admin --email admin@example.com &&
        airflow scheduler &
        airflow webserver --port 8080 --workers 1 &
        uvicorn app:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: